server:
  port:
    9099
spring:
  data:
    mongodb:
      uri: mongodb+srv://myAtlasDBUser:Ravi@myatlasclusteredu.bn9tlnb.mongodb.net/?retryWrites=true&w=majority
      database: Microservices_POC





